### ISSUE TITLE
Models: Sqw/qe-util: search pseudo pot with lower letter name, report duplicate choice

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/iFit#30]

**Comment by farhi** [comment]
This is to avoid using a pseudo instead of an other (e.g. thinking of SSSP but using other).

**Comment by farhi** [comment]
CaF2 calculation failed with qe_ase and error:
[ASE/Phonopy] Computing step 0/2
Moving  atom #0   Ca     to  [0.01, 0.0, 0.0]

sqw_phonons_get_forces: ETA 2264:26:17, ending on 27-Jul-2017 11:10:58. move 1/36 [3%]
```
[ASE/Phonopy] Computing step 1/2
Moving  atom #4   F      to  [0.01, 0.0, 0.0]
Traceback (most recent call last):
  File "/var/www/html/ifit-web-services/upload/sqw_phonons_c0txT/sqw_phonons_forces_iterate.py", line 24, in <module>
    ret = ifit.phonon_run_phonopy(ph, single=True)
  File "/data/www/html/ifit-web-services/upload/sqw_phonons_c0txT/ifit.py", line 889, in phonon_run_phonopy
    forces = cell.get_forces()
  File "/usr/lib/python2.7/dist-packages/ase/atoms.py", line 688, in get_forces
    forces = self._calc.get_forces(self)
  File "/usr/lib/python2.7/dist-packages/ase/calculators/calculator.py", line 354, in get_forces
    return self.get_property('forces', atoms)
  File "/usr/lib/python2.7/dist-packages/ase/calculators/calculator.py", line 398, in get_property
    result = self.results[name]
KeyError: 'forces'
```
which is related to the naming of the pseudo for F: **F_pbe_v1.4.uspp.F.UPF**

So the ASE/QE interface should try other names, including <el>_<xc>... lower and upper caps.

**Comment by farhi** [comment]
Wrong guess.
Does not seem to be indeed the cause for failure. The pseudo are all found OK.

**Comment by farhi** [comment]
This works in fact perfectly...
