### ISSUE TITLE
Models: Sqw: phonons: support CP2K, bigDFT, Octopus, Siesta, Gulp, TurboMole ?

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/iFit#33]

**Comment by farhi** [comment]
ASE/CP2K requires 'cp2k_shell' to be found in the CP2K.command
see https://wiki.fysik.dtu.dk/ase/ase/calculators/cp2k.html

The cp2k_shall is not part of the Debian packages. Must compile CP2K and create Debian package if this is a route to follow.

**Comment by farhi** [comment]
Octopus seems also a good choice.

**Comment by farhi** [comment]
Support for Octopus is fully functional:

Ubuntu package: <http://octopus-code.org/wiki/Octopus_5.0.1> (current, linked with MPI and OpenMP)

Test in ASE:

- from ase.calculators.octopus import Octopus
- from ase.lattice import bulk
- system = bulk('Si', orthorhombic=True)
- calc = Octopus(label='silicon', Spacing=0.25, KPointsGrid=[[4, 4, 4]], KPointsUseSymmetries=True, Output='dos + density + potential', OutputFormat='xcrysden', DosGamma=0.1)
- system.set_calculator(calc)
- system.get_potential_energy()

**Comment by farhi** [comment]
Octopus only supports orthorombic structures

**Comment by farhi** [comment]
Siesta can also be considered:

- https://launchpad.net/siesta
- https://wiki.fysik.dtu.dk/ase/ase/calculators/siesta.html#module-ase.calculators.siesta

**Comment by farhi** [comment]
Octopus 5 not supported by ASE.
Octopus 6.0 compilation:

- install libgsl-dev
- ./configure
- make
- make install

**Comment by farhi** [comment]
Will consider **not do**:

- CP2K 2.6.2 Ubuntu 16.04 (from repo) does not seem to be functional with ASE. The '* READY' message is not detected and raises a stop.
- Octopus 6 (manual install) does not seem to be functional either...
- ASAP is limited in elements

**Comment by farhi** [comment]
**Siesta** easy to install:

- get tar.gz, extract
- go into Obj directory
- sh ../Src/obj_setup.sh
- cp gfortran.make arch.make

build serial.

To build with MPI, use:

- https://pelios.csx.cam.ac.uk/~mc321/siesta.html

Then get pseudo potentials (LDA/GGA-TM and LDA/GGA-FHI available).

**Comment by farhi** [comment]
**Siesta pseudo potentials** Obtained using NNIN/C Pseudopotential Virtual Vault

- http://nninc.cnf.cornell.edu/

Command used to retrieve:

- `wget -r -l1 --no-parent -A "*.psf" http://nninc.cnf.cornell.edu/psp_files/`

These are TM potentials. No (semi core, relativistic, nonlinear)

- *.psf:     LDA PZ  TM   74 elements
- *-gga.psf: GGA PBE TM   67 elements

Could also get psf files from: Abinit FHI conversion

- https://departments.icmab.es/leem/siesta/Databases/Pseudopotentials/Pseudos_GGA_Abinit
- https://departments.icmab.es/leem/siesta/Databases/Pseudopotentials/Pseudos_LDA_Abinit

**Comment by farhi** [comment]
Could try out turbomole which has an ASE calculator:

- http://www.turbomole.com/
- http://www.cosmologic-services.de/downloads/Turbomole-Demos/TmoleX42_Linux64_DEMO.bin

has a demo license for testing.

**Comment by farhi** [comment]
CP2K example with ASE

- https://www.cp2k.org/tools:ase

which is:

```
$ export ASE_CP2K_COMMAND="mpirun -n 2 cp2k_shell.popt"
$ python
>>> from ase.calculators.cp2k import CP2K
>>> from ase.build import molecule
>>> calc = CP2K()
>>> atoms = molecule('H2O', calculator=calc)
>>> atoms.center(vacuum=2.0)
>>> print(atoms.get_potential_energy())
-467.191035845
```
But fails with:

```
>>> calc = CP2K()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ase/calculators/cp2k.py", line 170, in __init__
    self._shell = Cp2kShell(self.command, self._debug)
  File "/usr/local/lib/python2.7/dist-packages/ase/calculators/cp2k.py", line 436, in __init__
    assert self.recv() == '* READY'
AssertionError
```

Requires fixing as MR.

Can also look at:

https://trac.fysik.dtu.dk/projects/ase/browser/trunk/ase/test/cp2k

**Comment by farhi** [comment]
The CP2K works mostly, but the pseudo basis sems to be updated:

the example ends with CP2K error:

```
 *********************************************************************
 *** ERROR in read_gth_potential (MODULE external_potential_types) ***
 *********************************************************************

 *** The requested atomic potential <GTH-LDA> for element <H> was not ***
 *** found in the potential file <POTENTIAL>                          ***
```

**Comment by farhi** [comment]
CP2K is now version 4.1. Ubuntu 16.04 provides 2.6 (from 2015).

**Comment by farhi** [comment]
CP2K 4 easy to install. Has a dependency solver (install in tools/toolchain). If works, could make a Debian package ??

**Comment by farhi** [comment]
Transferred into one issue per Calculator
