### ISSUE TITLE
Models: Phonons: add more results from ASE

### ISSUE THREAD

**Issue by farhi** [McStasMcXtrace/iFit#72]
Can complement sqw_phonons with:

- eDOS https://wiki.fysik.dtu.dk/ase/ase/dft/dos.html#more-details
- ThermoChem: https://wiki.fysik.dtu.dk/ase/ase/thermochemistry/thermochemistry.html and in particular the CrystalThermo

**Comment by farhi** [comment]
Added to sqw_phonons.m, **signal.Expression**

 'if (isfield(this.UserData, ''DOS'') && isempty(this.UserData.DOS)) || ~isempty(dir(fullfile(target, ''DOS.mat'')))', ...
    '  fprintf(fid, ''print "Computing crystal ThermoChemistry at T=%g [K]\\n"\n'', p(4));', ...
    '  fprintf(fid, ''dos = sio.loadmat("DOS.mat")\n'');', ...
    '  fprintf(fid, ''# read properties from pickle\n'');', ...
    '  fprintf(fid, ''fid = open("properties.pkl","rb")\n'');', ...
    '  fprintf(fid, ''properties = pickle.load(fid)\n'');', ...
    '  fprintf(fid, ''fid.close()\n'');', ...
    '  fprintf(fid, ''thermo = CrystalThermo(phonon_energies=dos["energy"]/1000.0, phonon_DOS=dos["DOS"])\n'');', ...
    '  fprintf(fid, ''S = thermo.get_entropy(temperature=%g)\n'', p(4));', ...
    '  fprintf(fid, ''F = thermo.get_helmholtz_energy(temperature=%g)\n'', p(4));', ...
    '  fprintf(fid, ''E = thermo.get_internal_energy(temperature=%g)\n'', p(4));', ...
    '  fprintf(fid, ''properties["entropy"] = S\n'');', ...
    '  fprintf(fid, ''properties["helmholtz_energy"] = F\n'');', ...
    '  fprintf(fid, ''properties["internal_energy"] = E\n'');', ...
    '  fprintf(fid, ''fid = open("properties.pkl","wb")\n'');', ...
    '  fprintf(fid, ''pickle.dump(properties, fid)\n'');', ...
    '  fprintf(fid, ''fid.close()\n'');', ...
    'end', ...

but it does not fully work: seems to have issue with storage type python <-> matlab
Traceback (most recent call last):
  File "/tmp/tp351d4f69_ebcc_4e9e_8163_9c5132f13456/sqw_phonons_eval.py", line 34, in <module>
    S = thermo.get_entropy(temperature=10)
  File "/usr/lib/python2.7/dist-packages/ase/thermochemistry.py", line 518, in get_entropy
    if omega_e[0] == 0.:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by farhi** [comment]
Done with commit https://github.com/McStasMcXtrace/iFit/commit/228990ed300ac6c070b04bfff19a5b56b8804f35
The computation is done for T=1:500 K when getting the DOS.
